### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by Finnsen** [StefanIndustries/HomeyTickTick#1]
The app worked fine for a while, but it has stopped adding tasks to the list. I have tried to delete the app and install it again, but when I log on I get an error message "Request failed with status code 500". Logging on to the iOS app and the website works fine.

**Comment by StefanIndustries** [comment]
Hi, I am currently aware of the issues. I have a solution already on a
different branch that will help solve the problem but I am on holiday. I
hope to get to it next week.

Op vr 28 jul. 2023 12:59 schreef Finnsen ***@***.***>:

**Comment by Finnsen** [comment]
No stress, just wanted to report it. Have a great vacation.

**Comment by StefanIndustries** [comment]
Hi,

Just wanted to report back to you that I am in contact with TickTick to hopefully solve some issues using the OpenAPI they provided. Not all functionality is available that I need for the Homey app to function correctly.
This might take a bit longer than I anticipated.

If I have a new version ready I will let you know.

**Comment by StefanIndustries** [comment]
I have fixed the current solution and will not wait for a response from TickTick.
It might break again in the future when TickTick changes their api once more but for now it seems to be working fine.

**Comment by Finnsen** [comment]
Works great. Thank you. 😃👍
